language: python
python:
  - "2.7"

  # disable the default submodule logic
git:
  submodules: false


before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev

install:
  - pip install -r requirements.txt

script:
  - cd scripts; python data_collection.py --province ชัยนาท --district มโนรมย์ --subdist ท่าฉนวน --village บ้านคลองรุน
