language: python
python:
  - "2.7"

  # disable the default submodule logic
git:
  submodules: false

script:
  - cd scripts; python data_collection.py --province ชัยนาท --district มโนรมย์ --subdist ท่าฉนวน --village บ้านคลองรุน
